### ISSUE TITLE
Add validation conditions in user registration form

### ISSUE THREAD

**Issue by akshay-nm** [SidSiddharthSingh/Automated-Toll-Payments#13]
Go through the [UserRegistrationForm.js](https://github.com/SidSiddharthSingh/Automated-Toll-Payments/blob/master/packages/user-registration-portal/src/components/UserRegistrationForm.js). The line you are interested in is 197.

We have multiple inputs fields in the form. The appearance of each of these fields is controlled by an object (checkout the object structure in the `userState` function arguments starting from line 48). 
Each such object has `isValid` property which indicates whether the current value of the input field is valid or not. Your job is add conditional logic which assigns true/false based on whether the input field is valid or not. 
At the moment, I have only added length checks which are comparatively lenient checks. For example, a string "asdasdasda" is not a valid contact number but the form will accept it as its length is equal to 10. 
So you have to add checks so that `isValid` property is set only if the value in the input field is valid.

**Comment by akshay-nm** [comment]
Any updates or doubts?
@SidSiddharthSingh

**Comment by SidSiddharthSingh** [comment]
Nope
